// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import "time"

type ContextKey struct {
	Name string `json:"name"`
}

type Developer struct {
	ID            int    `json:"id" gorm:"primaryKey"`
	DeveloperName string `json:"developer_name"`
	Games         []*Game  `json:"games" gorm:"many2many:game_developers;"`
}

type Game struct {
	ID          int        `json:"id" gorm:"primaryKey"`
	Title       string     `json:"title"`
	Genres      []*Genre     `json:"genres" gorm:"many2many:game_genres;"`
	Tag         string     `json:"tag"`
	Price       int        `json:"price"`
	Rating      int          `json:"rating"`
	Discount    int        `json:"discount"`
	Description string     `json:"description"`
	Developers  []*Developer `json:"developers" gorm:"many2many:game_developers;"`
	Publisher  *Publisher `json:"publisher" gorm:"foreignKey:PublisherID"`
	PublisherID int          `json:"publisher_id"`
	ReleaseDate time.Time  `json:"release_date"`
	Picture     string       `json:"picture"`
	Banner      string       `json:"banner"`
	System      string       `json:"system"`
}

type Genre struct {
	ID        int    `json:"id" gorm:"primaryKey"`
	GenreName string `json:"genre_name"`
	Games     []*Game  `json:"games" gorm:"many2many:game_genres;"`
}

type Publisher struct {
	ID            int    `json:"id" gorm:"primaryKey"`
	PublisherName string `json:"publisher_name"`
}
